theme: jekyll-theme-modernist
title: "Decentralizing Trust with Blockchains"
description: ""
show_downloads: false
google_analytics: UA-45547991-6
baseurl: "/watblockchain"
url: "https://rboutaba-cs.github.io"