theme: jekyll-theme-modernist
title: "Elastic Optical Network Virtualization"
description: "Creating the algorithmic foundations for next generation transport network slicing."
show_downloads: "false"
